name: Landing CI

on:
  push:
    branches:
      - main
    paths:
      - 'landing/**'
      - '.github/workflows/landing-ci.yml'
  pull_request:
    paths:
      - 'landing/**'
      - '.github/workflows/landing-ci.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: cachix/install-nix-action@v31

    - name: Build
      run: nix-shell nix/shell.nix --run "cd landing && hugo --gc --minify"
