name: Postgrest CI

on:
  push:
    branches:
      - main
    paths:
      - 'postgrest/**'
      - 'docker-compose.yml'
      - '.github/workflows/postgrest-ci.yml'
  pull_request:
    paths:
      - 'postgrest/**'
      - 'docker-compose.yml'
      - '.github/workflows/postgrest-ci.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANALIZA_POSTGREST_CONFIG: postgrest/postgrest.basic.conf
    steps:
    - uses: actions/checkout@v3

    - name: Build postgrest
      run: docker compose build postgrest

    - name: Run migrations
      run: docker compose up --abort-on-container-exit postgrest_flyway
