name: Postgrest CI

on:
  push:
    branches:
      - main
    paths:
      - 'postgrest/**'
      - 'docker-compose.yml'
      - '.github/workflows/postgrest-ci.yml'
  pull_request:
    paths:
      - 'postgrest/**'
      - 'docker-compose.yml'
      - '.github/workflows/postgrest-ci.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANALIZA_POSTGREST_CONFIG: postgrest/postgrest.basic.conf
      COMPOSE_ARGS: -f docker-compose.yml -f docker-compose.ci.yml
    steps:
    - uses: actions/checkout@v3

    - name: Build postgrest
      run: make build c=postgrest

    - name: Run migrations
      run: make ci_up_abort c=postgrest_flyway

    - name: Show Docker logs on failure
      if: failure()
      run: make logs
